-- ============================================================================
-- Disaster Response GIS Database Schema
-- ============================================================================
-- PostgreSQL + PostGIS database schema for disaster management system
-- Author: Generated by Claude Code
-- Date: 2024-01-15

-- ============================================================================
-- 1. Enable PostGIS Extension
-- ============================================================================

-- Enable PostGIS extension for spatial operations
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;

-- Verify PostGIS installation
SELECT PostGIS_version();

-- ============================================================================
-- 2. Create Tables
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Hospitals Table
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS hospitals CASCADE;

CREATE TABLE hospitals (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    phone VARCHAR(50),
    capacity INTEGER,  -- Number of beds
    emergency_ready BOOLEAN DEFAULT TRUE,
    facility_type VARCHAR(100),  -- General, Trauma Center, etc.

    -- Spatial column - Point geometry
    geom GEOGRAPHY(POINT, 4326) NOT NULL,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create spatial index for faster queries
CREATE INDEX idx_hospitals_geom ON hospitals USING GIST(geom);

-- Add trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_hospitals_updated_at BEFORE UPDATE ON hospitals
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Shelters Table
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS shelters CASCADE;

CREATE TABLE shelters (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    capacity INTEGER NOT NULL,  -- Maximum occupancy
    current_occupancy INTEGER DEFAULT 0,
    shelter_type VARCHAR(100),  -- Temporary, Permanent, Relief Camp
    contact_person VARCHAR(255),
    phone VARCHAR(50),
    has_food BOOLEAN DEFAULT TRUE,
    has_water BOOLEAN DEFAULT TRUE,
    has_medical BOOLEAN DEFAULT FALSE,

    -- Spatial column - Point geometry
    geom GEOGRAPHY(POINT, 4326) NOT NULL,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_shelters_geom ON shelters USING GIST(geom);
CREATE TRIGGER update_shelters_updated_at BEFORE UPDATE ON shelters
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Roads Table
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS roads CASCADE;

CREATE TABLE roads (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    road_type VARCHAR(50),  -- highway, primary, secondary, residential
    surface VARCHAR(50),  -- paved, unpaved, gravel
    lanes INTEGER,
    max_speed INTEGER,  -- km/h
    length REAL,  -- meters
    is_blocked BOOLEAN DEFAULT FALSE,  -- Blocked due to disaster
    condition VARCHAR(50),  -- good, moderate, poor, impassable

    -- Spatial column - LineString geometry
    geom GEOGRAPHY(LINESTRING, 4326) NOT NULL,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_roads_geom ON roads USING GIST(geom);
CREATE INDEX idx_roads_blocked ON roads(is_blocked);
CREATE TRIGGER update_roads_updated_at BEFORE UPDATE ON roads
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Administrative Boundaries Table
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS admin_boundaries CASCADE;

CREATE TABLE admin_boundaries (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    admin_level INTEGER,  -- 1=Country, 2=State, 3=District, 4=Block
    admin_type VARCHAR(50),  -- state, district, subdistrict
    population INTEGER,
    area_sqkm REAL,

    -- Spatial column - MultiPolygon geometry
    geom GEOGRAPHY(MULTIPOLYGON, 4326) NOT NULL,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_admin_boundaries_geom ON admin_boundaries USING GIST(geom);
CREATE INDEX idx_admin_boundaries_level ON admin_boundaries(admin_level);
CREATE TRIGGER update_admin_boundaries_updated_at BEFORE UPDATE ON admin_boundaries
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Flood Zones Table
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS flood_zones CASCADE;

CREATE TABLE flood_zones (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    severity VARCHAR(50) NOT NULL,  -- low, medium, high, critical
    water_level REAL,  -- meters
    affected_population INTEGER,
    start_time TIMESTAMP,
    end_time TIMESTAMP,  -- NULL if ongoing
    status VARCHAR(50) NOT NULL,  -- active, receding, cleared
    description TEXT,

    -- Spatial column - MultiPolygon geometry
    geom GEOGRAPHY(MULTIPOLYGON, 4326) NOT NULL,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_flood_zones_geom ON flood_zones USING GIST(geom);
CREATE INDEX idx_flood_zones_status ON flood_zones(status);
CREATE INDEX idx_flood_zones_severity ON flood_zones(severity);
CREATE TRIGGER update_flood_zones_updated_at BEFORE UPDATE ON flood_zones
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Cyclone Tracks Table
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS cyclone_tracks CASCADE;

CREATE TABLE cyclone_tracks (
    id SERIAL PRIMARY KEY,
    cyclone_name VARCHAR(255) NOT NULL,
    category INTEGER,  -- 1-5 Saffir-Simpson scale
    wind_speed INTEGER,  -- km/h
    pressure INTEGER,  -- hPa
    timestamp TIMESTAMP NOT NULL,
    forecast BOOLEAN DEFAULT FALSE,  -- TRUE if forecast, FALSE if actual
    status VARCHAR(50),  -- forming, active, weakening, dissipated

    -- Spatial column - Point geometry (cyclone center position)
    geom GEOGRAPHY(POINT, 4326) NOT NULL,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cyclone_tracks_geom ON cyclone_tracks USING GIST(geom);
CREATE INDEX idx_cyclone_tracks_name ON cyclone_tracks(cyclone_name);
CREATE INDEX idx_cyclone_tracks_status ON cyclone_tracks(status);
CREATE TRIGGER update_cyclone_tracks_updated_at BEFORE UPDATE ON cyclone_tracks
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Disaster Updates Table
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS disaster_updates CASCADE;

CREATE TABLE disaster_updates (
    id SERIAL PRIMARY KEY,
    disaster_type VARCHAR(50) NOT NULL,  -- flood, cyclone, earthquake, fire
    title VARCHAR(255) NOT NULL,
    description TEXT,
    severity VARCHAR(50) NOT NULL,  -- low, medium, high, critical
    status VARCHAR(50) NOT NULL,  -- active, monitoring, resolved
    affected_areas TEXT,  -- Comma-separated list of areas
    casualties INTEGER DEFAULT 0,
    displaced INTEGER DEFAULT 0,
    source VARCHAR(255),  -- Data source
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Optional spatial column - Can be point or polygon
    geom GEOGRAPHY(GEOMETRY, 4326),

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_disaster_updates_type ON disaster_updates(disaster_type);
CREATE INDEX idx_disaster_updates_status ON disaster_updates(status);
CREATE INDEX idx_disaster_updates_severity ON disaster_updates(severity);
CREATE INDEX idx_disaster_updates_timestamp ON disaster_updates(timestamp DESC);
CREATE TRIGGER update_disaster_updates_updated_at BEFORE UPDATE ON disaster_updates
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- 3. Insert Sample Data for Testing
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Sample Hospitals
-- ----------------------------------------------------------------------------
INSERT INTO hospitals (name, address, phone, capacity, emergency_ready, facility_type, geom) VALUES
('Central City Hospital', '123 Main St, Mumbai', '+91-22-12345678', 500, TRUE, 'General', ST_GeogFromText('POINT(72.8777 19.0760)')),
('Emergency Trauma Center', '456 Relief Rd, Delhi', '+91-11-98765432', 300, TRUE, 'Trauma Center', ST_GeogFromText('POINT(77.2090 28.6139)')),
('District Medical Center', '789 Health Ave, Bangalore', '+91-80-55555555', 200, TRUE, 'General', ST_GeogFromText('POINT(77.5946 12.9716)')),
('Regional Hospital', '321 Care Blvd, Chennai', '+91-44-44444444', 400, TRUE, 'Multi-specialty', ST_GeogFromText('POINT(80.2707 13.0827)')),
('Community Health Center', '555 Wellness St, Hyderabad', '+91-40-33333333', 150, FALSE, 'Community', ST_GeogFromText('POINT(78.4867 17.3850)'));

-- ----------------------------------------------------------------------------
-- Sample Shelters
-- ----------------------------------------------------------------------------
INSERT INTO shelters (name, address, capacity, current_occupancy, shelter_type, contact_person, phone, has_food, has_water, has_medical, geom) VALUES
('Safe Haven Shelter', 'Park Road, Mumbai', 1000, 250, 'Permanent', 'Rajesh Kumar', '+91-22-11111111', TRUE, TRUE, TRUE, ST_GeogFromText('POINT(72.8800 19.0800)')),
('Emergency Relief Camp', 'Stadium Complex, Delhi', 2000, 800, 'Temporary', 'Priya Sharma', '+91-11-22222222', TRUE, TRUE, TRUE, ST_GeogFromText('POINT(77.2100 28.6150)')),
('Community Center Shelter', 'School Grounds, Bangalore', 500, 120, 'Temporary', 'Amit Patel', '+91-80-66666666', TRUE, TRUE, FALSE, ST_GeogFromText('POINT(77.5950 12.9720)')),
('Flood Relief Shelter', 'Town Hall, Chennai', 800, 450, 'Relief Camp', 'Sunita Reddy', '+91-44-55555555', TRUE, TRUE, TRUE, ST_GeogFromText('POINT(80.2710 13.0830)')),
('Temporary Evacuation Center', 'Convention Center, Hyderabad', 1500, 600, 'Temporary', 'Vijay Singh', '+91-40-77777777', TRUE, TRUE, FALSE, ST_GeogFromText('POINT(78.4870 17.3860)'));

-- ----------------------------------------------------------------------------
-- Sample Roads
-- ----------------------------------------------------------------------------
INSERT INTO roads (name, road_type, surface, lanes, max_speed, length, is_blocked, condition, geom) VALUES
('National Highway 1', 'highway', 'paved', 4, 100, 50000, FALSE, 'good', ST_GeogFromText('LINESTRING(72.8777 19.0760, 72.8900 19.0900)')),
('Main Street', 'primary', 'paved', 2, 60, 5000, FALSE, 'good', ST_GeogFromText('LINESTRING(77.2090 28.6139, 77.2150 28.6200)')),
('Flood-Affected Road', 'secondary', 'paved', 2, 50, 3000, TRUE, 'impassable', ST_GeogFromText('LINESTRING(77.5946 12.9716, 77.6000 12.9800)')),
('Coastal Road', 'primary', 'paved', 2, 60, 8000, FALSE, 'moderate', ST_GeogFromText('LINESTRING(80.2707 13.0827, 80.2800 13.0900)')),
('Inner Ring Road', 'primary', 'paved', 4, 80, 15000, FALSE, 'good', ST_GeogFromText('LINESTRING(78.4867 17.3850, 78.5000 17.4000)'));

-- ----------------------------------------------------------------------------
-- Sample Administrative Boundaries
-- ----------------------------------------------------------------------------
INSERT INTO admin_boundaries (name, admin_level, admin_type, population, area_sqkm, geom) VALUES
('Maharashtra', 2, 'state', 112374333, 307713, ST_GeogFromText('MULTIPOLYGON(((72.6 18.5, 73.0 18.5, 73.0 19.0, 72.6 19.0, 72.6 18.5)))')),
('Delhi NCR', 2, 'state', 16787941, 1484, ST_GeogFromText('MULTIPOLYGON(((77.0 28.4, 77.4 28.4, 77.4 28.8, 77.0 28.8, 77.0 28.4)))')),
('Karnataka', 2, 'state', 61095297, 191791, ST_GeogFromText('MULTIPOLYGON(((77.3 12.7, 77.8 12.7, 77.8 13.2, 77.3 13.2, 77.3 12.7)))')),
('Tamil Nadu', 2, 'state', 72147030, 130060, ST_GeogFromText('MULTIPOLYGON(((80.0 12.8, 80.5 12.8, 80.5 13.3, 80.0 13.3, 80.0 12.8)))')),
('Telangana', 2, 'state', 35193978, 112077, ST_GeogFromText('MULTIPOLYGON(((78.2 17.1, 78.7 17.1, 78.7 17.6, 78.2 17.6, 78.2 17.1)))'));

-- ----------------------------------------------------------------------------
-- Sample Flood Zones
-- ----------------------------------------------------------------------------
INSERT INTO flood_zones (name, severity, water_level, affected_population, start_time, end_time, status, description, geom) VALUES
('Coastal Flood Zone A', 'high', 2.5, 50000, '2024-01-10 08:00:00', NULL, 'active', 'Severe coastal flooding due to heavy rainfall', ST_GeogFromText('MULTIPOLYGON(((72.85 19.05, 72.90 19.05, 72.90 19.10, 72.85 19.10, 72.85 19.05)))')),
('River Basin Flood', 'critical', 3.8, 120000, '2024-01-12 14:00:00', NULL, 'active', 'Critical flooding in river basin area', ST_GeogFromText('MULTIPOLYGON(((77.55 12.95, 77.60 12.95, 77.60 13.00, 77.55 13.00, 77.55 12.95)))'));

-- ----------------------------------------------------------------------------
-- Sample Cyclone Tracks
-- ----------------------------------------------------------------------------
INSERT INTO cyclone_tracks (cyclone_name, category, wind_speed, pressure, timestamp, forecast, status, geom) VALUES
('Cyclone Biparjoy', 3, 150, 965, '2024-01-15 06:00:00', FALSE, 'active', ST_GeogFromText('POINT(71.5 18.5)')),
('Cyclone Biparjoy', 3, 145, 968, '2024-01-15 12:00:00', TRUE, 'active', ST_GeogFromText('POINT(71.8 18.8)')),
('Cyclone Biparjoy', 2, 130, 975, '2024-01-16 00:00:00', TRUE, 'weakening', ST_GeogFromText('POINT(72.2 19.2)'));

-- ----------------------------------------------------------------------------
-- Sample Disaster Updates
-- ----------------------------------------------------------------------------
INSERT INTO disaster_updates (disaster_type, title, description, severity, status, affected_areas, casualties, displaced, source, timestamp, geom) VALUES
('flood', 'Severe Flooding in Coastal Areas', 'Heavy monsoon rains have caused severe flooding in multiple coastal districts. Emergency services are active.', 'high', 'active', 'Mumbai, Thane, Raigad', 12, 25000, 'IMD', '2024-01-15 08:30:00', ST_GeogFromText('POINT(72.8777 19.0760)')),
('cyclone', 'Cyclone Biparjoy Approaching West Coast', 'Category 3 cyclone expected to make landfall in next 24 hours. Evacuations in progress.', 'critical', 'active', 'Gujarat Coast, Maharashtra Coast', 5, 50000, 'IMD', '2024-01-15 10:00:00', ST_GeogFromText('POINT(71.5 18.5)')),
('earthquake', 'Moderate Earthquake Near Delhi', 'Magnitude 4.5 earthquake recorded. No major damage reported.', 'medium', 'monitoring', 'Delhi NCR, Haryana', 0, 0, 'National Seismological Centre', '2024-01-14 16:45:00', ST_GeogFromText('POINT(77.2090 28.6139)'));

-- ============================================================================
-- 4. Create Useful Views
-- ============================================================================

-- View for available shelter capacity
CREATE OR REPLACE VIEW shelter_availability AS
SELECT
    id,
    name,
    capacity,
    current_occupancy,
    (capacity - current_occupancy) AS available_capacity,
    ROUND(100.0 * current_occupancy / NULLIF(capacity, 0), 2) AS occupancy_rate,
    has_food,
    has_water,
    has_medical,
    ST_AsGeoJSON(geom)::json AS geometry
FROM shelters
WHERE current_occupancy < capacity;

-- View for active disasters
CREATE OR REPLACE VIEW active_disasters AS
SELECT
    disaster_type,
    severity,
    COUNT(*) AS count,
    SUM(casualties) AS total_casualties,
    SUM(displaced) AS total_displaced
FROM disaster_updates
WHERE status = 'active'
GROUP BY disaster_type, severity;

-- View for blocked roads
CREATE OR REPLACE VIEW blocked_roads AS
SELECT
    id,
    name,
    road_type,
    condition,
    ST_AsGeoJSON(geom)::json AS geometry
FROM roads
WHERE is_blocked = TRUE;

-- ============================================================================
-- 5. Create Helper Functions
-- ============================================================================

-- Function to find nearest facilities
CREATE OR REPLACE FUNCTION find_nearest_facilities(
    facility_table TEXT,
    user_lat DOUBLE PRECISION,
    user_lon DOUBLE PRECISION,
    search_limit INTEGER DEFAULT 5
)
RETURNS TABLE(
    id INTEGER,
    name VARCHAR,
    distance_meters DOUBLE PRECISION
) AS $$
BEGIN
    RETURN QUERY EXECUTE format('
        SELECT
            id,
            name,
            ST_Distance(
                geom,
                ST_SetSRID(ST_Point(%s, %s), 4326)::geography
            ) AS distance_meters
        FROM %I
        ORDER BY distance_meters
        LIMIT %s
    ', user_lon, user_lat, facility_table, search_limit);
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- 6. Grant Permissions (adjust as needed)
-- ============================================================================

-- Grant all permissions to your application user
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO disaster_gis_user;
-- GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO disaster_gis_user;

-- ============================================================================
-- Schema creation complete!
-- ============================================================================

SELECT 'Database schema created successfully!' AS status;
