-- ============================================================================
-- Disaster Response GIS Database Schema
-- ============================================================================
-- PostgreSQL + PostGIS database schema for disaster management system
-- Author: Generated by Claude Code
-- Date: 2024-01-15

-- ============================================================================
-- 1. Enable PostGIS Extension
-- ============================================================================

-- Enable PostGIS extension for spatial operations
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;

-- Verify PostGIS installation
SELECT PostGIS_version();

-- ============================================================================
-- 2. Create Tables
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Hospitals Table
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS hospitals CASCADE;

CREATE TABLE hospitals (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    phone VARCHAR(50),
    capacity INTEGER,  -- Number of beds
    emergency_ready BOOLEAN DEFAULT TRUE,
    facility_type VARCHAR(100),  -- General, Trauma Center, etc.

    -- Spatial column - Point geometry
    geom GEOGRAPHY(POINT, 4326) NOT NULL,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create spatial index for faster queries
CREATE INDEX idx_hospitals_geom ON hospitals USING GIST(geom);

-- Add trigger to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_hospitals_updated_at BEFORE UPDATE ON hospitals
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Shelters Table
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS shelters CASCADE;

CREATE TABLE shelters (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address TEXT,
    capacity INTEGER NOT NULL,  -- Maximum occupancy
    current_occupancy INTEGER DEFAULT 0,
    shelter_type VARCHAR(100),  -- Temporary, Permanent, Relief Camp
    contact_person VARCHAR(255),
    phone VARCHAR(50),
    has_food BOOLEAN DEFAULT TRUE,
    has_water BOOLEAN DEFAULT TRUE,
    has_medical BOOLEAN DEFAULT FALSE,

    -- Spatial column - Point geometry
    geom GEOGRAPHY(POINT, 4326) NOT NULL,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_shelters_geom ON shelters USING GIST(geom);
CREATE TRIGGER update_shelters_updated_at BEFORE UPDATE ON shelters
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Roads Table
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS roads CASCADE;

CREATE TABLE roads (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    road_type VARCHAR(50),  -- highway, primary, secondary, residential
    surface VARCHAR(50),  -- paved, unpaved, gravel
    lanes INTEGER,
    max_speed INTEGER,  -- km/h
    length REAL,  -- meters
    is_blocked BOOLEAN DEFAULT FALSE,  -- Blocked due to disaster
    condition VARCHAR(50),  -- good, moderate, poor, impassable

    -- Spatial column - LineString geometry
    geom GEOGRAPHY(LINESTRING, 4326) NOT NULL,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_roads_geom ON roads USING GIST(geom);
CREATE INDEX idx_roads_blocked ON roads(is_blocked);
CREATE TRIGGER update_roads_updated_at BEFORE UPDATE ON roads
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Administrative Boundaries Table
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS admin_boundaries CASCADE;

CREATE TABLE admin_boundaries (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    admin_level INTEGER,  -- 1=Country, 2=State, 3=District, 4=Block
    admin_type VARCHAR(50),  -- state, district, subdistrict
    population INTEGER,
    area_sqkm REAL,

    -- Spatial column - MultiPolygon geometry
    geom GEOGRAPHY(MULTIPOLYGON, 4326) NOT NULL,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_admin_boundaries_geom ON admin_boundaries USING GIST(geom);
CREATE INDEX idx_admin_boundaries_level ON admin_boundaries(admin_level);
CREATE TRIGGER update_admin_boundaries_updated_at BEFORE UPDATE ON admin_boundaries
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Flood Zones Table
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS flood_zones CASCADE;

CREATE TABLE flood_zones (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255),
    severity VARCHAR(50) NOT NULL,  -- low, medium, high, critical
    water_level REAL,  -- meters
    affected_population INTEGER,
    start_time TIMESTAMP,
    end_time TIMESTAMP,  -- NULL if ongoing
    status VARCHAR(50) NOT NULL,  -- active, receding, cleared
    description TEXT,

    -- Spatial column - MultiPolygon geometry
    geom GEOGRAPHY(MULTIPOLYGON, 4326) NOT NULL,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_flood_zones_geom ON flood_zones USING GIST(geom);
CREATE INDEX idx_flood_zones_status ON flood_zones(status);
CREATE INDEX idx_flood_zones_severity ON flood_zones(severity);
CREATE TRIGGER update_flood_zones_updated_at BEFORE UPDATE ON flood_zones
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Cyclone Tracks Table
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS cyclone_tracks CASCADE;

CREATE TABLE cyclone_tracks (
    id SERIAL PRIMARY KEY,
    cyclone_name VARCHAR(255) NOT NULL,
    category INTEGER,  -- 1-5 Saffir-Simpson scale
    wind_speed INTEGER,  -- km/h
    pressure INTEGER,  -- hPa
    timestamp TIMESTAMP NOT NULL,
    forecast BOOLEAN DEFAULT FALSE,  -- TRUE if forecast, FALSE if actual
    status VARCHAR(50),  -- forming, active, weakening, dissipated

    -- Spatial column - Point geometry (cyclone center position)
    geom GEOGRAPHY(POINT, 4326) NOT NULL,

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_cyclone_tracks_geom ON cyclone_tracks USING GIST(geom);
CREATE INDEX idx_cyclone_tracks_name ON cyclone_tracks(cyclone_name);
CREATE INDEX idx_cyclone_tracks_status ON cyclone_tracks(status);
CREATE TRIGGER update_cyclone_tracks_updated_at BEFORE UPDATE ON cyclone_tracks
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ----------------------------------------------------------------------------
-- Disaster Updates Table
-- ----------------------------------------------------------------------------
DROP TABLE IF EXISTS disaster_updates CASCADE;

CREATE TABLE disaster_updates (
    id SERIAL PRIMARY KEY,
    disaster_type VARCHAR(50) NOT NULL,  -- flood, cyclone, earthquake, fire
    title VARCHAR(255) NOT NULL,
    description TEXT,
    severity VARCHAR(50) NOT NULL,  -- low, medium, high, critical
    status VARCHAR(50) NOT NULL,  -- active, monitoring, resolved
    affected_areas TEXT,  -- Comma-separated list of areas
    casualties INTEGER DEFAULT 0,
    displaced INTEGER DEFAULT 0,
    source VARCHAR(255),  -- Data source
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Optional spatial column - Can be point or polygon
    geom GEOGRAPHY(GEOMETRY, 4326),

    -- Timestamps
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_disaster_updates_type ON disaster_updates(disaster_type);
CREATE INDEX idx_disaster_updates_status ON disaster_updates(status);
CREATE INDEX idx_disaster_updates_severity ON disaster_updates(severity);
CREATE INDEX idx_disaster_updates_timestamp ON disaster_updates(timestamp DESC);
CREATE TRIGGER update_disaster_updates_updated_at BEFORE UPDATE ON disaster_updates
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- Schema creation complete!
-- ============================================================================
